spring:
  application:
    name: grpc-demo
  grpc:
    server:
      port: 9090   # default, shown explicitly for clarity
    client:
      channel:
        hello:
          # logical channel name "hello" (see @ImportGrpcClients in GrpcDemoApplication)
          # resolves to this real target
          target: static://localhost:9090
        getOrder:
          target: static://localhost:9090
  data:
    mongodb:
      uri: mongodb+srv://myAtlasDBUser:myatlas-001@myatlasclusteredu.h33zgbz.mongodb.net/?appName=myAtlasClusterEDU
      database: demo
      show-sql: true
  kafka:
    enabled: false
    listener:
      auto-startup: true
    properties:
      sasl.mechanism: SCRAM-SHA-256
      bootstrap.servers: kafka-3d3dad9a-sajithjayaraman74-192c.l.aivencloud.com:13703
      sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username='avnadmin' password='AVNS_v4EywHz-wycHum3wwo8';
      security.protocol: SASL_SSL
      session.timeout.ms: 45000
      acks: all
      truststore.location: classpath:/client-certs/ca.pem
      truststore.password: AVNS_v4EywHz-wycHum3wwo8
      ssl.truststore.type: PEM
  logging:
    level:
      org.springframework.web.client.RestTemplate: DEBUG
      org.springframework.kafka: DEBUG
      org.springframework.data.mongodb.core.MongoTemplate: WARN
      org.springframework.data.mongodb.repository.Query: WARN